### PR TITLE
changed contribution wording

### PR DESCRIPTION
**Pull request by nquinlan**
I changed the wording a little to something a little more "businessy" or whatever. Take a look let me know what you think.

### CODE REVIEW

**Comment by elbuo8** [comment]
Seems good to me. A bit bound to us. I will make it so its a big more customizable.

**Comment by nquinlan** [comment]
Rockin'

**Comment by nquinlan** [comment]
Just FYI, Gmail is marking the current wording as phishing. 
image

**Comment by elbuo8** [comment]
Dammit Gmail!

On Wednesday, May 14, 2014, Nick Quinlan notifications@github.com wrote:

> Just FYI, Gmail is marking the current wording as phishing.
> [image: image]https://cloud.githubusercontent.com/assets/829864/2978094/811e5716-dbb4-11e3-8e90-6fd801c86afc.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/elbuo8/contribot/pull/7#issuecomment-43144455
> .

## 

Yamil Asusta
@elbuo8 https://twitter.com/elbuo8

**Pull request merged**
